Task 2
Danila-Peshev/my-favorite-movies-front pull request #2
Opened 2024-07-22 11:49 UTC by Danila-Peshev

task-2

2024-07-23 07:23 UTC, Isidora25 requested changes

2024-07-23 07:23 UTC, Isidora25 commented on src/fillLocalStorage.tsx
> +const Users = [
```suggestion
const USERS = [
```
в PascalCase именуются либо классы, либо компоненты

2024-07-23 07:23 UTC, Isidora25 commented on src/index.tsx
> +
вынеси в отдельный файл - это улучшит читаемость

2024-07-23 07:23 UTC, Isidora25 commented on src/index.tsx
> +export const Context = createContext<State>({
подскажи, а для чего тебе нужен store? 
ты легко реализуешь логику работы и проверки текущего юзера с помощью только контекста в реакте 
кроме того, потом когда ты будешь прикручивать бэк, ты будешь использовать apollo-client  с хуками и там тоже можно прекрасно обойтись без сторов

2024-07-23 07:23 UTC, Isidora25 commented on src/pages/Home/Home.tsx
> +        <h1 className='text-4xl font-bold'>Пользователь {store.user.email}, добро пожаловать на сайт "Моё любимое кино"!</h1>
добавь интернационализацию в проект с помощью lingui или i18n

2024-07-23 07:23 UTC, Isidora25 commented on src/pages/Home/Home.tsx
> +        <div>
этот div кажется лишний здесь

2024-07-23 07:23 UTC, Isidora25 commented on src/pages/Login/Login.tsx
> +      <img src={logo} className="mx-auto size-40 mb-10 rounded-full"></img>
```suggestion
      <img src={logo} className="mx-auto size-40 mb-10 rounded-full" />
```
плюс нужно добавлять alt аттрибут  к изображениям

2024-07-23 07:23 UTC, Isidora25 commented on src/pages/Login/Login.tsx
> +              className="border border-neutral-300 shadow-sm h-10 text-2xl"></input>
вот тут ты придумал велосипед немного 
это самая обычная форма 
для работы с формами в реакт удобно использовать react-final-form например

2024-07-23 07:23 UTC, Isidora25 commented on src/pages/Login/Login.tsx
> +            <label>Запомнить меня</label>
это не надо реализовывать

2024-07-23 07:23 UTC, Isidora25 commented on src/pages/Login/Login.tsx
> +            <div className="grow"></div>
это точно здесь нужно?

2024-07-23 07:23 UTC, Isidora25 commented on src/pages/Login/Login.tsx
> +      </div>
это тоже пропускаем

2024-07-23 07:23 UTC, Isidora25 commented on src/services/AuthService.ts
> +        }
это работа валидации в форме, а не сервиса аутентификации

2024-07-23 07:23 UTC, Isidora25 commented on src/services/AuthService.ts
> +export default class AuthService {
так как ты используешь функциональные компоненты, не стоит миксовать стили и использовать классы 
тут отлично подойдет просто функция или хук

2024-07-23 07:23 UTC, Isidora25 commented on src/services/AuthService.ts
> +        }
а это очень небезопасная штука. когда ты показываешь пользователю, что у тебя нет в базе такой почты, ты даешь возможность брут форсом подобрать имейлы из твоей базы 
так что лучше возвращать обобщенное сообщение об ошибке

2024-07-23 18:07 UTC, Danila-Peshev commented on src/pages/Login/Login.tsx
> +            <div className="grow"></div>
Он служил как распорка, чтобы кнопка была в правой стороне. Т.к. "Запомнить меня" сейчас нет, то его тоже убрал.

2024-07-23 18:07 UTC, Danila-Peshev commented on src/index.tsx
> +export const Context = createContext<State>({
В интернете примерах увидел много пример со стором. Сейчас всё на контексте.

2024-07-23 18:08 UTC, Danila-Peshev commented on src/services/AuthService.ts
> +export default class AuthService {
Прошу прощения, после java тяжело привыкнуть к этому😅

2024-07-23 18:09 UTC, Danila-Peshev commented on src/services/AuthService.ts
> +        }
Я старался всё делать по ТЗ, я думал это очень важно, поэтому и сделал как во вложенном примере.

2024-07-24 07:14 UTC, Isidora25 requested changes

2024-07-24 07:14 UTC, Isidora25 commented on public/locales/en/translation.json
> +    "input-error-empty": "No field should be empty",
это не критично, но обычно ключи в camelCase в json

2024-07-24 07:14 UTC, Isidora25 commented on src/components/AuthContext.tsx
> +const AuthContext = createContext<AuthContextType>({} as AuthContextType);
`as` это всегда такой хак, в котором нужно быть 100 процентов уверенным
если ты уверен, что пустой объект не выстрелит тебе в ногу в моменты обращения к нему за переменной - это хорошо 
но лучше не злоупотреблять этим хаком и инициализировать контекст с falsy значениями, а обработчики сделать необязательными

2024-07-24 07:14 UTC, Isidora25 commented on src/components/switch_language/LanguageSwitcher.tsx
> +    const changeLanguage = useCallback((lng: string) => {
если changeLanguage не используется нигде кроме useEffect не выноси это из него, не создавай доп зависимости для перерендера

2024-07-24 07:14 UTC, Isidora25 commented on src/components/switch_language/LanguageSwitcher.tsx
> +    const [activeLanguage, setActiveLanguage] = useState('ru');
тут классно подойдет использование union type из typeScript 
```suggestion
type Language = 'ru' | 'en'


    const [activeLanguage, setActiveLanguage] = useState<Language>('ru');
```

тогда в activeLanguage не попадет ничего кроме 'ru' или 'en'

2024-07-24 07:14 UTC, Isidora25 commented on src/components/switch_language/SwitchLanguageButton.tsx
> +  }
два раза одно и то же

2024-07-24 07:14 UTC, Isidora25 commented on src/pages/Login/Login.tsx
> +  const onSubmit = async (values: { email: any; password: any; }) => {
`any` нужно использовать так же аккуратно как `as`
в данном случае ты просто выключил тайп скрипт 
только в крайних случаях, когда ты не знаешь, например, что приходит из апи 
а в этом случае ты точно знаешь, как будет тип у email  и password

2024-07-24 07:14 UTC, Isidora25 commented on src/pages/Login/Login.tsx
> +    }
лучше такого плана валидацию делать с помощью функции на филд validate  и блокировать кнопку submit пока форма не будет валидной полностью 
иначе это не оч юзер френдли 
юзер понимает, что данные не валидные только после нажатия на кнопку сабмит

2024-07-24 07:14 UTC, Isidora25 commented on src/pages/Login/Login.tsx
> +                  </Field>
DRY 
Сделай компонент, в котором будет label  и input + сообщение об ошибке и передавай в prop component в Field

2024-07-24 07:14 UTC, Isidora25 commented on src/components/switch_language/SwitchLanguageButton.tsx
папки лучше называть в kabab-case

2024-07-26 06:39 UTC, Isidora25 commented on src/pages/Login/Login.tsx
> +                    disabled={submitting || pristine}
кажется, все кнопка все еще активна, если форма невалидна

2024-07-26 11:37 UTC, Isidora25 approved these changes

2024-07-26 11:49 UTC, reshetov requested changes

2024-07-26 11:49 UTC, reshetov commented on package.json
>      "@types/node": "^16.18.101",
Стразу - коммит как и ветка должны называться понятно, можно длинно, но обязательно - понято
`task5`  ровно как и `small-fixes`, `my-last-commit-in-this-week` не несут в себе смыслвой нагрузки и по ним нельзя понять что именно было сделано. А это ОЧЕНЬ может пригодится если тебе нужно найти "кто сломал эту кнопку полгода назад"

2024-07-26 11:49 UTC, reshetov commented on src/components/AuthContext.tsx
> +    const [user, setUser] = useState<User | null>(null);
Отступы везде это 2 пробела, а не tab. Tab'ы у всех разные

2024-07-26 11:49 UTC, reshetov commented on src/components/AuthContext.tsx
> +        if (optinalUser && password === optinalUser?.password) {
тут safe-оператор смысла не имеет, ты шагом раньше проверяешь что optionalUser есть

2024-07-26 11:49 UTC, reshetov commented on src/pages/Home/Home.tsx
> +        <h1 className='text-4xl font-bold'>{t('welcome', { user: user?.email })}</h1>
Тут ? тоже лишний, у тебя этот компонент закрыть PrivateRoute, сюдя никак "не-пользователь" не зайдет

2024-07-26 12:51 UTC, Danila-Peshev commented on src/pages/Home/Home.tsx
> +        <h1 className='text-4xl font-bold'>{t('welcome', { user: user?.email })}</h1>
Есои уберу ts будет ругаться на 'user' is possibly 'null'

2024-07-26 13:46 UTC, reshetov approved these changes

2024-07-26 13:51 UTC, merged