Implementing a service for interacting with the api
Danila-Peshev/my-favorite-movies-front pull request #3
Opened 2024-07-30 08:35 UTC by Danila-Peshev

Task 3

2024-07-31 07:04 UTC, Isidora25 requested changes

2024-07-31 07:04 UTC, Isidora25 commented on src/components/switch-language/LanguageContext.tsx
> +  activeLanguage: Language;
```suggestion
  language: Language;
```

2024-07-31 07:04 UTC, Isidora25 commented on src/services/MovieService.ts
> +  }));
не оч поняла задумку. но если уж тебе очень надо мапать, переписывай сразу в camelCase

2024-07-31 07:04 UTC, Isidora25 commented on src/services/MovieService.ts
> +    total_result: data.total_results,
то же замечание про camelCase

2024-07-31 07:04 UTC, Isidora25 commented on src/services/MovieService.ts
> +  }
вообще странно вызывать функцию, которая отдает что-то по id не передавая туда никаких id 
если id нет, то функцию вообще не стоит вызывать, а параметр ids должен быть обязательным

2024-07-31 07:04 UTC, Isidora25 commented on src/services/MovieService.ts
> +  const paginatedResults = results.slice(startIndex, endIndex);
20 -> magic number, непонятно, что это такое. такие числовые значения обычно выносят в переменные с говорящим именем.

2024-07-31 07:04 UTC, Isidora25 commented on src/types/movie-api-types/OnlyMovie.ts
> +  vote_count: number
тебе не нужно описывать ВЕСЬ объект, который от апи возвращается 
опиши, только то, что нужно

2024-07-31 18:13 UTC, Danila-Peshev commented on src/services/MovieService.ts
> +    total_result: data.total_results,
Я старался сделать названия такими же, как у TMBD. Хорошо, переименую

2024-08-01 01:07 UTC, Danila-Peshev commented on src/services/MovieService.ts
> +  }));
Привожу все полученные фильмы с API к SimpleMovie, чтобы не было лишней информации

2024-08-01 10:06 UTC, Isidora25 requested changes

2024-08-01 10:06 UTC, Isidora25 commented on src/services/MovieService.ts
> +  const data = await fetchFromApi('/genre/movie/list', { language: language });
```suggestion
  const data = await fetchFromApi('/genre/movie/list', { language });
```

2024-08-01 10:06 UTC, Isidora25 commented on src/components/switch-language/LanguageSwitcher.tsx
> +  }, [language, i18n]);
это тоже все двинь в контекст

2024-08-01 10:06 UTC, Isidora25 commented on src/services/MovieService.ts
> +    voteCount: movie.vote_count,
тут можно короче с деструктуризацией - 
```
const simpleMovies: SimpleMovie[] = data.results.map(({id,backdrop_path,genre_ids, overview  }: Movie) => ({
     id, 
     backdropPath: movie.backdrop_path,
    genre_ids: movie.genre_ids,
    overview
```

2024-08-01 10:06 UTC, Isidora25 commented on src/services/MovieService.ts
> +  const maxMoviesOnPage = 20;
выноси неизменяемые константы за функцию и используй UPPER_SNAKE_CASE

2024-08-01 10:06 UTC, Isidora25 commented on src/services/MovieService.ts
> +    genreIds: data.genres.map((genre: { id: number; }) => genre.id),
```suggestion
    genreIds: data.genres.map(( { id }) =>id),
```

2024-08-01 11:14 UTC, Isidora25 requested changes

2024-08-01 11:14 UTC, Isidora25 commented on src/services/MovieService.ts
> +      genre_ids,
а куда пропал camelCase?)

2024-08-02 12:38 UTC, Isidora25 approved these changes

2024-08-02 13:25 UTC, reshetov approved these changes

2024-08-02 13:25 UTC, reshetov commented on .env.example
> +REACT_APP_ACCESS_TOKEN_AUTH=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5NjIwNmU1MDYxMjdhY2FlMjU4NTQ2MDA3N2VhMTRmOSIsIm5iZiI6MTcyMjEwMzUyOS4xMTQwNSwic3ViIjoiNjY5ZThiMzY2NzkzMDMxN2RmZjM3NmU0Iiwic2NvcGVzIjpbImFwaV
Если это боевой токен убери его от греха. Использую заглушки вида `xxxxxxxx`

2024-08-02 13:26 UTC, merged