Development of the home page
Danila-Peshev/my-favorite-movies-front pull request #4
Opened 2024-08-05 07:48 UTC by Danila-Peshev

Implementation of the main page and all her components

2024-08-05 11:14 UTC, Isidora25 requested changes

2024-08-05 11:14 UTC, Isidora25 commented on src/assets/views-images/block_view.png
для иконок лучше использовать svg 
они не теряют в качестве и всегда будут выглядеть хорошо
при этом не будут занимать много места

2024-08-05 11:14 UTC, Isidora25 commented on src/assets/views-images/row_view.png
то же самое про svg

2024-08-05 11:14 UTC, Isidora25 commented on src/global-components/NavBar.tsx
а чем global-components отличаются от components? 
обычно если components папка лежит сразу в src, это уже означает, что компоненты глобального уровня 
все неглобальные компоненты должны являться подпапками тех страниц/компонентов, к которым они относятся

2024-08-05 11:14 UTC, Isidora25 commented on src/components/movies-block/MoviesBlock.tsx
> +  const { user, getWatchedMoviesId, getFavoriteMoviesId } = useAuth();
непонятно, почему контекст аутентификации, возвращает еще и айдишники фильмов 
это совершенно другой смысловой контекст

2024-08-05 11:14 UTC, Isidora25 commented on src/components/movies-block/MoviesBlock.tsx
> +    500
почему 500? почему не 5? почему не 10 миллионов?

2024-08-05 11:14 UTC, Isidora25 commented on src/components/movies-block/MoviesBlock.tsx
> +      if (isOnAddedPage) {
мне очень непонятно, что такое AddedPage. Добавленная страница? куда она добавлена?
переименуй, пожалуйста

2024-08-05 11:14 UTC, Isidora25 commented on src/components/movies-block/MoviesBlock.tsx
> +        }
слишком усложняешь компонент. он получается слишком многозадачным. у компонента/класса/функции в идеале (к которому стоит стремиться) должна быть одна задача. в твоем случае, задаче компонента - отобразить список фильмов. компоненту должно быть все равно, что это за фильмы - избранные, не избранные. другиими словами, тебе нужно вынести логику запроса фильмов на уровень выше

2024-08-05 11:14 UTC, Isidora25 commented on src/components/movies-block/OneMovie.tsx
> +const MovieBlock: FC<MovieBlockProps> = ({
файл называется OneMovie, а сам компонент иначе. Переименуй, плиз

2024-08-05 11:14 UTC, Isidora25 commented on src/components/movies-block/OneMovie.tsx
> +              })}
Это очень сложно читать 
либо вынеси в компонент, который принимает проп isBlockView и меняет внешний вид, когда isBlockView меняется
либо это два разных компонента, один для блочного вида, второй для списка

2024-08-05 11:14 UTC, Isidora25 commented on src/components/movies-block/OneMovie.tsx
> +      </div>
condition ? <div>...</div> : null

2024-08-05 11:14 UTC, Isidora25 commented on src/components/movies-block/PaginationBlock.tsx
> +  };
это функция хелпер, вынеси ее из тела компонента, иначе она будет пересоздаваться при каждом ререндере

2024-08-05 11:14 UTC, Isidora25 commented on src/components/movies-block/PaginationBlock.tsx
> +          {t("firstPage")}
зачем так сложно) 
арабские цифры прекрасно справляются с индикацией номера страницы)

2024-08-05 11:14 UTC, Isidora25 commented on src/pages/home/GenresBlock.tsx
> +        ))}
не забывай про атрибут key

2024-08-12 04:12 UTC, Danila-Peshev commented on src/components/movies-block/MoviesBlock.tsx
> +      if (isOnAddedPage) {
Имеется ввиду - блок на странице добавления фильмов, если да то убираются кнопки у фильмов. Если честно не знаю как правильно это заименовать, подскажи пожалуйста как лучше)

2024-08-12 07:54 UTC, Isidora25 requested changes

2024-08-12 07:54 UTC, Isidora25 commented on src/components/UserContext.tsx
> +export const UserProvider = ({ children }: { children: ReactNode }) => {
а зачем тебе этот контекст, если тут нет ни одного своего стейта? 
вынеси просто все эти функции в сервис - общий файл и импортируй их точно так же как этот контекст 
контекст нужен для хранения глобального стейта, здесь он выглядит излишним

2024-08-12 07:54 UTC, Isidora25 commented on src/pages/home/Home.tsx
> +  );
а зачем оно?

2024-08-12 07:54 UTC, Isidora25 commented on src/pages/home/Home.tsx
> +      setStatus((prevStatus) => ({ ...prevStatus, loadingMovies: false }));
обработку ошибок от апи лучше спрятать в сервис работы с апи и возвращать эти ошибки сразу оттуда. если они тут нужны, конечно же

2024-08-12 07:54 UTC, Isidora25 commented on src/pages/home/Home.tsx
> +  }, [page, user?.favoriteMoviesId]);
не нужно хранить инфо по любимым жанрам, фильмам в объекте юзер 
да, они зависят от юзера, но это разные области

2024-08-12 07:54 UTC, Isidora25 commented on src/pages/home/Home.tsx
> +        {loadingGenres || loadingMovies ? (
зачем тебе два разных стейта для лоадинга, если ты их используешь одновременно?

2024-08-12 07:54 UTC, Isidora25 commented on src/pages/home/Home.tsx
> +        ) : errorGenres || errorMovies ? (
тот же вопрос про ошибку, но от стейта для ошибки лучш вообще избавиться

2024-08-12 07:54 UTC, Isidora25 commented on src/pages/home/movies-block/BlockViewOneMovie.tsx
> +      )}
а почему наоборот? 
если show, то обычно показывают что-то, а у тебя null)

2024-08-12 07:54 UTC, Isidora25 commented on src/pages/home/movies-block/BlockViewOneMovie.tsx
> +      )}
либо переименуй флаг в hide, либо поправь тернарник

2024-08-12 07:54 UTC, Isidora25 commented on src/pages/home/movies-block/RowViewOneMovie.tsx
> +    <div
очень много одинакового кода, как в BlockViewOnMevie 
точно нельзя стилями обыграть два разных вида? 
у тебя нет никаких ограничений в виде мокапов от дизайнеров, сделай себе жизнь легче и сделай эти два комопнента максимально одинаковыми, только меняй расположение контента 
если вдруг тебе понадобится добавить новый элемент для отоборажения фильма, тебе придется делать это дважды
если компонент будет один, то всего лишь один раз

2024-08-12 11:22 UTC, Danila-Peshev commented on src/pages/home/Home.tsx
> +  );
Ответ от tmdb может вернуть больше 1 тыс. страниц, а когда обращаешься к ним со страницей больше 500 они возвращают invalid page error 22, поэтому сделал ограничение.

2024-08-12 11:25 UTC, Danila-Peshev commented on src/pages/home/Home.tsx
> +      setStatus((prevStatus) => ({ ...prevStatus, loadingMovies: false }));
Хорошо, я их добавил, потому что на некоторых браузерах без VPN обрывало попытку запроса, и чтобы юзер не ждал вечной загрузки, решил обрабатывать ошибки

2024-08-12 11:36 UTC, Danila-Peshev commented on src/pages/home/Home.tsx
> +  }, [page, user?.favoriteMoviesId]);
Мне получается нужно из localStorage сделать бд?
Просто для этого потребуется сделать три таблицы: юзеры, юзерЖанр и юзерФильм.
Т.к. это LS придется обновить функции получения жанров и фильмов по id юзера.
Мне сделать это, или лучше подождать пока дойду до бэка?

2024-08-12 11:38 UTC, Danila-Peshev commented on src/pages/home/movies-block/RowViewOneMovie.tsx
> +    <div
Могу, но только в className контейнеров везде будут проверки на isBlockView, это правильный подход, или есть другой способ?

2024-08-12 11:41 UTC, Isidora25 commented on src/pages/home/Home.tsx
> +  }, [page, user?.favoriteMoviesId]);
нет, тебе просто не нужно возвращать это в объект юзер, функция getFavMoviesIds должна возвращать только айдишники фильмов, без объекта юзера

2024-08-12 11:42 UTC, Isidora25 commented on src/pages/home/movies-block/RowViewOneMovie.tsx
> +    <div
придумай себе дизайн такой, чтобы от isBlockView зависели только стили корневого контейнера

2024-08-12 12:12 UTC, Danila-Peshev commented on src/pages/home/Home.tsx
> +  }, [page, user?.favoriteMoviesId]);
Эти функции возвращают массив чисел, без объекта юзера.
А функции с добавлением/удалением обновляют данные в LS.
Если сделать всё без юзера, то в LS придётся создать связные таблицы, где в аргументах функциях будут крутиться только id юзеров.

Мне тяжело это понять, просто я привык, что по запросам указывается id пользователя и возвращается в ответе массив id жанров/фильмов и готово.
Не понимаю как это сделать без участия юзера, если нужно получить id избранных фильмов/жанров по id этого юзера.

Как нужно сделать, объясни подробнее пожалуйста, я потерялся в этом вопросе 😥

2024-08-14 11:31 UTC, Isidora25 requested changes

2024-08-14 11:31 UTC, Isidora25 commented on src/components/AuthContext.tsx
> +  const [user, setUser] = useState<User>({} as User);
а зачем тебе тут пустой объект? нормально же все было с null
а сейчас всякие костыли лезут в виде проверки наличия ключей объекта

2024-08-14 11:31 UTC, Isidora25 commented on src/components/AuthContext.tsx
> +export const useAuth = () => useContext(AuthContext);
почему убрал дженерик?

2024-08-14 11:31 UTC, Isidora25 commented on src/services/UserDataService.ts
> +  .map((value: { genre_id: any; }) => value.genre_id);
избавься от any плиз

2024-08-14 13:52 UTC, Danila-Peshev commented on src/components/AuthContext.tsx
> +export const useAuth = () => useContext(AuthContext);
Не увидел в попытках менять AuthContext, вернул.

2024-08-14 14:14 UTC, Isidora25 approved these changes

2024-08-14 14:36 UTC, reshetov commented on src/pages/home/movies-block/OneMovie.tsx
> +          src={`https://image.tmdb.org/t/p/w400${movie.posterPath}`}
Передвинь в константу или вообще в env

2024-08-15 07:14 UTC, reshetov approved these changes

2024-08-15 07:14 UTC, merged