Auth
Danila-Peshev/my-favorite-movies-front pull request #7
Opened 2024-09-17 08:26 UTC by Danila-Peshev

2024-09-17 11:57 UTC, Isidora25 requested changes

2024-09-17 11:57 UTC, Isidora25 commented on src/components/AuthContext.tsx
> +  const {data, loading, error} = useQuery(GET_USER)
вынеси все это в касотмный хук и положи рядома с описанием квери. Тем самым ты вынесешь работу с апи на отдельный уровени

2024-09-17 11:57 UTC, Isidora25 commented on src/components/AuthContext.tsx
> +      setUser({id: responseQuery.data.getUser.id, email: responseQuery.data.getUser.email});
не надо так усложнять, ты можешь передернуть квери с помощью refetch

2024-09-17 11:57 UTC, Isidora25 commented on src/components/AuthContext.tsx
> +    localStorage.setItem("token", responseMutation.data.login.token)
проверь, тут в случае ошибки может не быть объекта data

2024-09-17 11:57 UTC, Isidora25 commented on src/components/AuthContext.tsx
> +    return false
это тебе уже не нужно скорее всего

2024-09-18 11:30 UTC, Isidora25 requested changes

2024-09-18 11:30 UTC, Isidora25 commented on src/gql-hooks/useLogin.ts
> +
сделай два разных хука 
1. useLogin
2. useGetUser

если тебе придется вызывать их по отдельности, будет неудобно

2024-09-18 11:30 UTC, Isidora25 commented on src/gql-hooks/useLogin.ts
> +    fetchPolicy: "no-cache",
cache-and-network не работает?
"no-cache" ты вырубаешь кеширование совсем, а значит вырубаешь оптимизацию

2024-09-18 12:04 UTC, Isidora25 approved these changes

2024-09-18 12:18 UTC, reshetov approved these changes

2024-09-18 12:18 UTC, merged