Link front to back (interaction user via apollo)
Danila-Peshev/my-favorite-movies-front pull request #8
Opened 2024-09-19 11:41 UTC by Danila-Peshev

2024-09-19 13:27 UTC, Isidora25 requested changes

2024-09-19 13:27 UTC, Isidora25 commented on src/pages/add/Add.tsx
> +  }
жестоко, чего сразу логаут-то?

2024-09-19 13:27 UTC, Isidora25 commented on src/pages/home/Home.tsx
> +  if (
если ты таким образом хотел очищать токен, если случилась ошибка авторизации, то лучше это делать на уровне apollo client 
потому что 
1. ошибки могут быть разные 
2. замучаешь это проверять при каждом вызове хука

2024-09-19 13:27 UTC, Isidora25 commented on src/pages/home/Home.tsx
> +    await refetchUserMovies();
этого, кстати, можно избежать, если toggleWatchMovie мутация изменяет тот же dto, что и refetchUserMovies 
почитай про это в документации apollo

2024-09-19 13:27 UTC, Isidora25 commented on src/pages/home/Home.tsx
> +      setMoviesResponse(movies);
тебе больше не нужно хранить стейт для ответа с бэка, потому что у тебя теперь все в хуках, которые хранят стейт аполло

2024-09-19 13:27 UTC, Isidora25 commented on src/pages/home/Home.tsx
> +    if (user && !isLoadingUserMovies) {
а точно проверка юзера все еще актуальна?

2024-09-19 13:27 UTC, Isidora25 commented on src/pages/home/Home.tsx
> +              )}
DRY

2024-09-19 13:27 UTC, Isidora25 commented on src/pages/home/Home.tsx
> +                .map((movie: { movieId: number }) => movie.movieId)}
старайся не мапить прямо в рендере 
тогда каждый ререндер массив будет создаваться заново

2024-09-19 13:27 UTC, Isidora25 commented on src/pages/home/Home.tsx
> +                .filter((movie: { isWatched: boolean }) => movie.isWatched)
а зачем { isWatched: boolean } ? 
ts должен автоматически определять, что лежит в movie 
если не определяет, значит у тебя где-то в хуках не хватает типов для описания возвратов с бэка

2024-09-19 13:27 UTC, Isidora25 commented on src/pages/home/movies-block/MoviesBlock.tsx
> +          : movies.map((simpleMovie, index) => (
читабельнее, если поменяешь местами 
movies.length ? movies.map : t("notSingleMovieWasFound")

2024-09-19 14:48 UTC, Danila-Peshev commented on src/pages/home/Home.tsx
> +      setMoviesResponse(movies);
Так я пока только взаимодействие с юзером переделал, с фильмами во второй части

2024-09-23 08:08 UTC, reshetov requested changes

2024-09-23 08:08 UTC, reshetov commented on src/gql-hooks/useUserGenres.ts
> +  const userGenres = userGenresData?.getUserGenres.map(
У тебя тут судя по safe-оператору getUserGenres может и не быть, но тем не менее ты отважно его мапаешь потом, тогда уж делай через (...getUserGenres || []).map, а то в твоем случае свалится может

2024-09-23 08:08 UTC, reshetov commented on src/gql-hooks/useUserMovies.ts
> +  const userMovies = userMoviesData?.getUserMovies.map(
см. выше коммент про  .map

2024-09-23 08:08 UTC, reshetov commented on src/gql-hooks/useUserMovies.ts
> +  const watchedUserMovies = userMoviesData?.getUserMovies
Ну и тут

2024-09-23 08:28 UTC, reshetov requested changes

2024-09-23 08:28 UTC, reshetov commented on src/gql-hooks/useUserGenres.ts
> +  const userGenres = (userGenresData.getUserGenres || []).map(
Не не, safe тут убирать не нужно по идее. Ты его для чего добавлял - для того, чтобы если userGenresData не придет (будет undefined), у тебя не получился вызов `undefined.getUserGenres` (что выкинет ошибку).  А в текущей твоей реализации это как раз и произойдет и `||` тут не поможет, исключение остановит выполнение кода

2024-09-23 08:36 UTC, reshetov approved these changes

2024-09-23 08:36 UTC, merged